### ISSUE TITLE
The error to predict the protein and RNA structure

### ISSUE THREAD

**Issue by lj734999889** [uw-ipd/RoseTTAFold2NA#21]
When I use this code, the machine reports wrong, shown as below, did you know how to resolve this? Thank you very much.

Traceback (most recent call last):
  File "/home/software/RoseTTAFold2NA/network/predict.py", line 345, in <module>
    pred.predict(inputs=args.inputs, out_prefix=args.prefix, ffdb=ffdb)
  File "/home/software/RoseTTAFold2NA/network/predict.py", line 146, in predict
    msa_i, ins_i = parse_a3m(a3m_i, unzip=False)
  File "/home/software/RoseTTAFold2NA/network/parsers.py", line 221, in parse_a3m
    msa = np.array([list(s) for s in msa], dtype='|S1').view(np.uint8)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (722,) + inhomogeneous part.

**Comment by lj734999889** [comment]
I‘ve solved this problem. That's caused by my own wrong .a3m files.
