### ISSUE TITLE
RuntimeError: Class values must be smaller than num_classes.

### ISSUE THREAD

**Issue by adimil** [uw-ipd/RoseTTAFold2NA#27]
Hello,

I am getting the following error message when running on GPU:
```
Traceback (most recent call last):
  File "/home/.../RoseTTAFold2NA/network/predict.py", line 345, in <module>
    pred.predict(inputs=args.inputs, out_prefix=args.prefix, ffdb=ffdb)
  File "/home/.../RoseTTAFold2NA/network/predict.py", line 225, in predict
    self._run_model(Ls, msa_orig, ins_orig, t1d, t2d, xyz_t, xyz_t[:,0], alpha_t, "%s_%02d"%(out_prefix, i_trial))
  File "/home/.../RoseTTAFold2NA/network/predict.py", line 233, in _run_model
    seq, msa_seed_orig, msa_seed, msa_extra, mask_msa = MSAFeaturize(
  File "/home/.../RoseTTAFold2NA/network/data_loader.py", line 116, in MSAFeaturize
    raw_profile = raw_profile.float().mean(dim=0)
RuntimeError: CUDA error: device-side assert triggered CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```
Or when running on CPU:
```
Traceback (most recent call last):
  File "/home/.../RoseTTAFold2NA/network/predict.py", line 345, in <module>
    pred.predict(inputs=args.inputs, out_prefix=args.prefix, ffdb=ffdb)
  File "/home/.../RoseTTAFold2NA/network/predict.py", line 225, in predict
    self._run_model(Ls, msa_orig, ins_orig, t1d, t2d, xyz_t, xyz_t[:,0], alpha_t, "%s_%02d"%(out_prefix, i_trial))
  File "/home/.../RoseTTAFold2NA/network/predict.py", line 233, in _run_model
    seq, msa_seed_orig, msa_seed, msa_extra, mask_msa = MSAFeaturize(
  File "/home/.../RoseTTAFold2NA/network/data_loader.py", line 115, in MSAFeaturize
    raw_profile = torch.nn.functional.one_hot(msa, num_classes=NAATOKENS)
RuntimeError: Class values must be smaller than num_classes.
```

Do you have any idea what might cause this and how to fix?

Thanks!

**Comment by mmagnus** [comment]
I got the same problem, I didn't find the solution yet.

**Comment by bifxcore** [comment]
Same here, though I'm getting @adimil 's 'CPU' error when I'm running on GPU:

RoseTTAFold2NA/network/parsers.py:116: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  msa[msa == "U"] = 30
Running on GPU
Traceback (most recent call last):
  File "RoseTTAFold2NA/network/predict.py", line 374, in <module>
    pred.predict(inputs=args.inputs, out_prefix=args.prefix, ffdb=ffdb)
  File "RoseTTAFold2NA/network/predict.py", line 250, in predict
    self._run_model(Ls, msa_orig, ins_orig, t1d, t2d, xyz_t, xyz_t[:,0], alpha_t, same_chain, mask_t_2d, "%s_%02d"%(out_prefix, i_trial))
  File "RoseTTAFold2NA/network/predict.py", line 256, in _run_model
    seq, msa_seed_orig, msa_seed, msa_extra, mask_msa = MSAFeaturize(
  File "RoseTTAFold2NA/network/data_loader.py", line 118, in MSAFeaturize
    raw_profile = torch.nn.functional.one_hot(msa, num_classes=NAATOKENS)
RuntimeError: Class values must be smaller than num_classes.

**Comment by bifxcore** [comment]
How do I fix the "Class values must be smaller than num_classes." error? 

msa size: torch.Size([6142, 1064])
num_classes: 32

It looks like I need to either reduce the msa size or increase NAATOKENS drastically... that does not sound right?

**Comment by fdimaio** [comment]
Hello,  can you try the latest version?  This was a bug where 32 was hardcoded.  If this does not work, can you post your MSA?

**Comment by bifxcore** [comment]
@fdimaio I downloaded the package last week, so I just updated network/parsers.py and restarted predict.py.

I'm not getting the error from https://github.com/uw-ipd/RoseTTAFold2NA/issues/15


Running on GPU
Traceback (most recent call last):
  File "RoseTTAFold2NA/network/predict.py", line 374, in <module>
    pred.predict(inputs=args.inputs, out_prefix=args.prefix, ffdb=ffdb)
  File "RoseTTAFold2NA/network/predict.py", line 160, in predict
    msa_i, ins_i = parse_fasta(a3m_i, rna_alphabet=is_rna, dna_alphabet=is_dna)
  File "RoseTTAFold2NA/network/parsers.py", line 119, in parse_fasta
    assert (np.all(msa<=31))
AssertionError

**Comment by bifxcore** [comment]
RNA MSA attached.

[tRNA_Glu.afa.gz](https://github.com/uw-ipd/RoseTTAFold2NA/files/11840539/tRNA_Glu.afa.gz)

**Comment by bifxcore** [comment]
@fdimaio something is amiss with parsers.py . I have checked that my RNA alignment only contains allowed characters:
perl -ne 'next if /^>/; print unless /[UCGA-]+/' tRNA_Glu.unfilter.afa
returns nothing. Sequences are fine.

I added a few debugging statements to parsers.py. This is the output:

Running on GPU
is RNA alphabet? True
max value : 89
largest values out of all rows :
[30 30 30 31 31 89 31 31 30 30 30 89 30 31 30 30 31 30 89 89 89 82 30 30
 30 30 30 89 89 87 31 30 30 89 31 31 31 30 30 30 31 30 83 82 89 30 31 89
 30 82 30 30 30 75 89 30 30 82 31 89 30 31 30 83 30 31 86 66 83 30 82 31
 77 31 31 27]

  File "RoseTTAFold2NA/network/parsers.py", line 125, in parse_fasta
    assert (np.all(msa<=31))
AssertionError

How can a value in msa be > 31 when the alphabet array index ranges from 0 to 31?

**Comment by bifxcore** [comment]
Fixed this issue with a quick and dirty hack:
```
# remove RNA sequences with illegal characters from alignment
perl -ne ' if (/^>/) {$h = $_} else { if (/^[ NUCGA-]+$/i) {print $h, $_} }' my_crappy_RNA_file.afa  > tRNA_Glu.afa
```

now fighting https://github.com/uw-ipd/RoseTTAFold2NA/issues/13 ;-)
