### ISSUE TITLE
run RNA prediction error 

### ISSUE THREAD

**Issue by fengzk0425** [uw-ipd/RoseTTAFold2NA#8]
bash -x ../run_RF2NA.sh test R:test.fa
output:
+ python /home/ubuntu/RoseTTAFold2NA/network/predict.py -inputs R:/home/ubuntu/RoseTTAFold2NA/example/Rtest/Rtest.afa -prefix /home/ubuntu/RoseTTAFold2NA/example/Rtest/models/model -model /home/ubuntu/RoseTTAFold2NA/network/weights/RF2NA_sep22.pt -db /home/ubuntu/RoseTTAFold2NA/pdb100_2021Mar03/pdb100_2021Mar03
Running on GPU
Traceback (most recent call last):
  File "/home/ubuntu/RoseTTAFold2NA/network/predict.py", line 345, in <module>
    pred.predict(inputs=args.inputs, out_prefix=args.prefix, ffdb=ffdb)
  File "/home/ubuntu/RoseTTAFold2NA/network/predict.py", line 225, in predict
    self._run_model(Ls, msa_orig, ins_orig, t1d, t2d, xyz_t, xyz_t[:,0], alpha_t, "%s_%02d"%(out_prefix, i_trial))
  File "/home/ubuntu/RoseTTAFold2NA/network/predict.py", line 233, in _run_model
    seq, msa_seed_orig, msa_seed, msa_extra, mask_msa = MSAFeaturize(
  File "/home/ubuntu/RoseTTAFold2NA/network/data_loader.py", line 135, in MSAFeaturize
    sample_mono = torch.randperm((N-1)//nmer, device=msa.device)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by fdimaio** [comment]
Can you run this final command on CPU?  What happens?  I'm not able to replicate this unfortunately.
