### ISSUE TITLE
example posiible failure `conda activate RF2NA && ../run_RF2NA.sh t000_ protein.fa R:RNA.fa`

### ISSUE THREAD

**Issue by truatpasteurdotfr** [uw-ipd/RoseTTAFold2NA#9]
Hello

running the above commands yields:
stdout:
```
Running HHblits
Running PSIPRED
Running hhsearch
Running rMSA (lite)
Running RoseTTAFold2NA to predict structures
Running on GPU
           plddt    best
RECYCLE  0   0.875  -1.000
RECYCLE  1   0.893   0.875
RECYCLE  2   0.897   0.893
RECYCLE  3   0.899   0.897
RECYCLE  4   0.900   0.899
RECYCLE  5   0.900   0.900
RECYCLE  6   0.902   0.900
RECYCLE  7   0.902   0.902
RECYCLE  8   0.901   0.902
RECYCLE  9   0.901   0.902
Done
```
stderr:
```
/pasteur/appa/scratch/tru/RoseTTAFold2NA/network/parsers.py:116: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  msa[msa == "U"] = 30
/pasteur/appa/scratch/tru/miniconda3/envs/RF2NA/lib/python3.8/site-packages/e3nn/o3/_spherical_harmonics.py:82: UserWarning: FALLBACK path has been taken inside: compileCudaFusionGroup. This is an indication
 that codegen Failed for some reason.
To debug try disable codegen fallback path via setting the env variable `export PYTORCH_NVFUSER_DISABLE=fallback`
To report the issue, try enable logging via setting the envvariable ` export PYTORCH_JIT_LOG_LEVEL=manager.cpp`
 (Triggered internally at  /opt/conda/conda-bld/pytorch_1659484810403/work/torch/csrc/jit/codegen/cuda/manager.cpp:237.)
  sh = _spherical_harmonics(self._lmax, x[..., 0], x[..., 1], x[..., 2])
```

**Comment by truatpasteurdotfr** [comment]
running with `export PYTORCH_NVFUSER_DISABLE=fallback` yields:
stdout:
```
Running HHblits
Running PSIPRED
Running hhsearch
Running rMSA (lite)
Running RoseTTAFold2NA to predict structures
Running on GPU
           plddt    best
```
stderr:
```
/pasteur/appa/scratch/tru/RoseTTAFold2NA/network/parsers.py:116: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  msa[msa == "U"] = 30
Traceback (most recent call last):
  File "/pasteur/appa/scratch/tru/RoseTTAFold2NA/network/predict.py", line 345, in <module>
    pred.predict(inputs=args.inputs, out_prefix=args.prefix, ffdb=ffdb)
  File "/pasteur/appa/scratch/tru/RoseTTAFold2NA/network/predict.py", line 225, in predict
    self._run_model(Ls, msa_orig, ins_orig, t1d, t2d, xyz_t, xyz_t[:,0], alpha_t, "%s_%02d"%(out_prefix, i_trial))
  File "/pasteur/appa/scratch/tru/RoseTTAFold2NA/network/predict.py", line 269, in _run_model
    logit_s, logit_aa_s, logit_pae, init_crds, alpha_prev, _, pred_lddt_binned, msa_prev, pair_prev, state_prev = self.model(
  File "/pasteur/appa/scratch/tru/miniconda3/envs/RF2NA/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/pasteur/appa/scratch/tru/RoseTTAFold2NA/network/RoseTTAFoldModel.py", line 96, in forward
    msa, pair, xyz, alpha_s, xyzallatom, state = self.simulator(
  File "/pasteur/appa/scratch/tru/miniconda3/envs/RF2NA/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/pasteur/appa/scratch/tru/RoseTTAFold2NA/network/Track_module.py", line 430, in forward
    msa_full, pair, xyz, state, alpha = self.extra_block[i_m](msa_full, pair,
  File "/pasteur/appa/scratch/tru/miniconda3/envs/RF2NA/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/pasteur/appa/scratch/tru/RoseTTAFold2NA/network/Track_module.py", line 356, in forward
    xyz, state, alpha = self.str2str(msa.float(), pair.float(), xyz.detach().float(), state.float(), idx, top_k=top_k)
  File "/pasteur/appa/scratch/tru/miniconda3/envs/RF2NA/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/pasteur/appa/scratch/tru/miniconda3/envs/RF2NA/lib/python3.8/site-packages/torch/amp/autocast_mode.py", line 12, in decorate_autocast
    return func(*args, **kwargs)
  File "/pasteur/appa/scratch/tru/RoseTTAFold2NA/network/Track_module.py", line 223, in forward
    shift = self.se3(G, node.reshape(B*L, -1, 1), l1_feats, edge_feats)
  File "/pasteur/appa/scratch/tru/miniconda3/envs/RF2NA/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/pasteur/appa/scratch/tru/RoseTTAFold2NA/network/SE3_network.py", line 83, in forward
    return self.se3(G, node_features, edge_features) #, clamp_d=clamp_d)
  File "/pasteur/appa/scratch/tru/miniconda3/envs/RF2NA/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/pasteur/appa/scratch/tru/miniconda3/envs/RF2NA/lib/python3.8/site-packages/se3_transformer-1.0.0-py3.8.egg/se3_transformer/model/transformer.py", line 163, in forward
  File "/pasteur/appa/scratch/tru/miniconda3/envs/RF2NA/lib/python3.8/site-packages/se3_transformer-1.0.0-py3.8.egg/se3_transformer/model/basis.py", line 167, in get_basis
  File "/pasteur/appa/scratch/tru/miniconda3/envs/RF2NA/lib/python3.8/site-packages/se3_transformer-1.0.0-py3.8.egg/se3_transformer/model/basis.py", line 58, in get_spherical_harmonics
  File "/pasteur/appa/scratch/tru/miniconda3/envs/RF2NA/lib/python3.8/site-packages/e3nn/o3/_spherical_harmonics.py", line 180, in spherical_harmonics
    return sh(x)
  File "/pasteur/appa/scratch/tru/miniconda3/envs/RF2NA/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/pasteur/appa/scratch/tru/miniconda3/envs/RF2NA/lib/python3.8/site-packages/e3nn/o3/_spherical_harmonics.py", line 82, in forward
    sh = _spherical_harmonics(self._lmax, x[..., 0], x[..., 1], x[..., 2])
RuntimeError: tensor_type->scalarType().has_value() INTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1659484810403/work/torch/csrc/jit/codegen/cuda/type_promotion.cpp":111, please report a bug to PyTo
rch. Missing Scalar Type information

```

**Comment by fdimaio** [comment]
Sorry, this is fixed now.
